StreamFi-x/streamfi-frontend

CONTRIBUTING.md, README.md
**Closes #2**
I was assigned to contribute to the **StreamFi** project by improving documentation and providing clearer contribution guidelines. Specifically, I worked on enhancing the `README.md` and `CONTRIBUTING.md` files to make them more structured and informative for new contributors.  
- **Updated README.md** to provide a detailed overview of StreamFi, including project structure, setup instructions, and branch naming conventions.  
- **Created CONTRIBUTING.md** with clear guidelines on how to contribute, including issue creation, pull request process, and label definitions.  
- **Added Installation Instructions** to help new contributors set up the development environment smoothly.  
- **Provided Branch Naming Conventions** to maintain consistency in Git workflows.  
- **Linked …
=> feat: update readme

.github/pull_request_template.md
*Closes #issue_number_here*
🚨Please review the [contribution guideline](/CONTRIBUTING.md) for this repository.
=> Doc pull request template

app/Components/Benefits.tsx, app/page.tsx
Closes #9
Build the Benefits Section Component 
- Add Benefit Component in app/components
- Use this component in app/page
=> feat: Add benefit section component

README.md
added an icon and a link to the license
*Closes #issue_number_here*
=> docs: conrtibuting

app/(landing)/page.tsx, app/settings/layout.tsx, app/settings/page.tsx, components/landing-page/HeroSection.tsx, components/landing-page/Waitlist.tsx
Update the page structure and directory
=> chore: update page directory

components/landing-page/Community.tsx
Your PR template looks well-structured and includes all the key information! To make your contribution even more compelling and comprehensive, here’s a cleaned-up and polished version:
---
Description
This pull request addresses the issue: Updating the Community Section Button Links  
Closes #39 
- Updated the `Community` section buttons to link to the respective X (Twitter), Discord, and Telegram community handles.
- Ensured the buttons open in a new tab with proper security measures (`target="_blank"` and `rel="noopener noreferrer"`).  
---
- Update the Community section to use correct URLs for X, Discord, and Telegram community pages.
- Ensure the buttons open in a new tab securely.
- Modified the `CommunitySection` component to include updated `<a>` tags with the correct URLs.
- …
=> Update Community section buttons to link to X, Discord, and Telegram

components/landing-page/Navbar.tsx
*Closes #41*
Implement Mobile View for Navbar and Ensure Full Responsiveness Across All Devices
Modified the Navbar page to make it responsive using the design provided in the figma file
=> chore: made navbar responsive

components/landing-page/FrequentlyAskedQuestions.tsx, data/landing-page/frequentlyAskedQuestions.ts
…Qs Section
This PR improves the FAQs section by implementing mobile responsiveness. Adjustments were made to ensure a better user experience across different screen sizes.
*Closes #45 *
Implement Mobile View & Responsiveness for FAQs Section
-Implemented the mobile view for the FAQs section first 
-Ensured the layout adapts perfectly on mobile devices. 
-Made the FAQs section fully responsive across mobile, tablet, and desktop views.
-Used the Accordion component from ShadCN for the FAQ items.
=> Modified FAQ section to Implement Mobile View & Responsiveness for FA

app/not-found.tsx, components/error/ActionButtons.tsx, components/error/AnimatedTitle.tsx, components/error/BackgroundNumber.tsx, components/error/LoadingDots.tsx, components/error/NotFound.tsx, components/error/NotFoundAnimation.tsx
*Closes #75 *
Create a custom 404 error page that displays a visually appealing error message when users visit a non-existent route, includes a "Go Back Home" button, is fully responsive, and has a unique UI with animations.
- Created seven new files:
- `app/not-found.tsx`: Entry point that leverages Next.js App Router's built-in 404 handling
- `components/error/PageNotFoundContent.tsx`: Container component for the 404 page UI
- `components/error/NotFoundAnimation.tsx`: Animation wrapper component
- `components/error/BackgroundNumber.tsx`: Background "404" display component
- `components/error/AnimatedTitle.tsx`: Main "404" title component
- `components/error/ActionButtons.tsx`: Navigation buttons component
- `components/error/LoadingDots.tsx`: Animated dots component at the bottom of the …
=> Implement-a-Custom-404-Page

components/landing-page/Waitlist.tsx
*Closes #47 *
Change the styling of the section to allow the section responsive for mobile and bigger screen
Implement responsive design for the Waitlist section with focus on mobile view
- Implemented mobile-first design approach for the Waitlist section
- Updated the Waitlist.tsx component to ensure proper responsiveness across all screen sizes (mobile, tablet, desktop)
- Refined the styling to match the Figma design specifications
- Ensured the Join Waitlist form functions correctly with proper email input validation
- Added appropriate media queries for responsive breakpoints
- Tested the component across various screen sizes to verify proper adaptation
- Optimized button and input field positioning for mobile devices
🚨Please review the [[contribution …
=> feat: made the waitilist section responsive

app/api/users/[wallet]/route.ts, app/api/users/register/route.ts, utils/validators.ts
*Closes #92 *
Create User Registration Schema & API (with Wallet Login Support)
- Created dynamic API endpoints under app/api/users/register/route.ts and app/api/users/[wallet]/route.ts.
- Used NextRequest and NextResponse for modern Next.js API handling (since we're in App Router mode).
- Debugged an initial issue where req.body was appearing as a ReadableStream (common in Next.js App Router).
- Inserted new users into the database securely.
- Wrote a reusable function checkExistingTableDetail() to check for existing entries based on any table, key, and value.
- Packaged query results into NextResponse.json() responses.
- Handled missing users gracefully with 404 error responses when appropriate …
=> Feat 92 registration

app/api/waitlist/subscribe/route.ts, components/landing-page/Waitlist.tsx, package.json, utils/models/waitlist.ts, utils/mongodb.ts, utils/send-email.ts
closes #101 
Made sure email template works and made some few tweaks to the api integration and error handling
=> Feat implemented and tested email template working

app/[username]/about/page.tsx, app/[username]/clips/page.tsx, app/[username]/layout.tsx, app/[username]/page.tsx, app/[username]/videos/page.tsx, app/[username]/watch.tsx/page.tsx, app/api/users/[wallet]/route.ts, app/explore/layout.tsx, app/settings/layout.tsx, components/auth/auth-provider.tsx, components/connectWallet.tsx, components/explore/Navbar.tsx, components/explore/ProfileModal.tsx, components/owner/profile/ChannelAbout.tsx, components/owner/profile/ChannelHome.tsx, components/settings/profile/profile-page.tsx, components/shared/profile/AboutSection.tsx, components/shared/profile/Banner.tsx, components/shared/profile/CustomizeChannelButton.tsx, components/shared/profile/EmptyState.tsx, components/shared/profile/ProfileHeader.tsx, components/shared/profile/StreamCard.tsx, components/shared/profile/TabsNavigation.tsx, components/stream/view-stream.tsx, components/ui/profileDropdown.tsx, components/viewer/profile/ChannelAbout.tsx, components/viewer/profile/ChannelHome.tsx
Closes #98 
Build the default public profile home page for a user when the stream is not live, following the layout and logic specified in the issue, with components scoped for future integration.
- Created the `HomeTab` component inside `components/viewer/profile`.
- Rendered dummy data for **Recent Streams** and **Popular Clips**.
- Implemented responsive grid layouts using Tailwind CSS.
- Added reusable sections with thumbnails, tags, and viewer counts.
- Handled the image layout using Next.js `Image` component.
- Incorporated styles and badge indicators for "Live" and viewer stats.
- Component is built with separation of structure and ready to mount conditionally for routing optimization.
=> feat: build profile page

app/api/users/register/route.ts, app/api/users/updates/[wallet]/route.ts, app/api/waitlist/subscribe/route.ts, app/api/waitlist/unsubscribe/route.ts, lib/Ddb.ts, package.json, scripts/setup-db.js, scripts/updateUserSchema.mjs, types/user.ts, utils/upload/Dcloudinary.ts, utils/userValidators.ts
PR Description:
Description
Closes #107 
Changes proposed
What were you told to do?
Reconfigure the register and login endpoints, update the users table schema, and implement the /api/user/update.ts endpoint with support for profile updates, avatar upload, and proper error handling.
What did you do?
Auth endpoints:
Ensured consistent schema handling for email, emailVerified, emailNotifications, and creator.
Added logic to insert registered user's email into the waitlist table.
Ensured secure password hashing and token issuance.
Database:
Updated db/schema.sql to include:
social_links (JSONB)
creator (JSONB)
email_notifications (BOOLEAN)
email_verified (BOOLEAN)
API Endpoint:
Created /api/user/update.ts to support full/partial updates by wallet.
Handled:
username, email, bio, streamKey, …
=> Feat: Reconfigure Auth Endpoints, Extend User Schema, and Implement Profile Update with Avatar Upload

app/api/users/register/route.ts, types/user.ts, utils/upload/Dcloudinary.ts, utils/userValidators.ts
=> fix build errors

app/api/debug/env/route.ts, app/api/debug/fix-db/route.ts, app/api/debug/livepeer-test/route.ts, app/api/debug/user-stream/route.ts, app/api/streams/[wallet]/route.ts, app/api/streams/chat/route.ts, app/api/streams/create/route.ts, app/api/streams/delete-get/route.ts, app/api/streams/delete/route.ts, app/api/streams/metrics/[streamId]/route.ts, app/api/streams/playback/[playbackId]/route.ts, app/api/streams/start/route.ts, app/api/streams/update/route.ts, app/api/streams/viewers/route.ts, app/stream/page.tsx, components/StreamTestComponent.tsx, db/schema.sql, lib/livepeer/server.ts, package.json
*Closes #154 *
Implement Livepeer streaming integration backend APIs and create frontend testing components for the StreamFi platform
- **Core Livepeer Integration** (`lib/livepeer/server.ts`): Created comprehensive Livepeer SDK integration with stream management functions
- **Stream Management APIs**: Implemented 10 API endpoints for complete streaming functionality:
- `app/api/streams/create/route.ts` - Create new streams with user validation
- `app/api/streams/start/route.ts` - Start/stop stream functionality
- `app/api/streams/[wallet]/route.ts` - Get stream data by wallet address
- `app/api/streams/playback/[playbackId]/route.ts` - Get playback sources for viewers
- `app/api/streams/update/route.ts` - Update stream metadata (title, description)
- `app/api/streams/delete/route.ts` - …
=> feat: built and integrated livepeer streaming custom api and then implemented a test environment for testing the endpoints

components/auth/auth-provider.tsx, components/explore/Navbar.tsx, components/settings/appearance/appearance.tsx, components/settings/profile/basic-settings-section.tsx, components/settings/profile/save-section.tsx, components/settings/profile/social-links-section.tsx, lib/theme-classes.ts
Closes #166 
Update the complete **Settings Page UI** and fix some minor functionalities based on design refinements.  
This includes changes in text color, padding, button styles, and some small but critical behavioral fixes in the form logic.
- Refactored the **Settings page** to use consistent padding, font sizes, and Tailwind utility classes
- Made small improvements to form functionality:
- Fixed issue where validation didn't show correctly on blur
- Disabled the **Save Changes** button when no changes are detected
- Ensured toggle and radio input values persist properly
- Improved accessibility with proper ARIA labels
=> fix: updated text and button colors on settings, and navbar

components/Home.test.tsx, jest.config.ts, jest.setup.ts, package.json
added jest and a demo test
_Closes #160 _
add jest to the entire projecet
added jest
=> fix:add jest and test with home.test.ts

app/explore/report-bug/page.tsx, app/report-bug/page.tsx, components/feedback/FeedbackHeader.tsx, components/feedback/FileUpload.tsx, components/feedback/ReportBugForm.tsx, components/ui/form.tsx, components/ui/select.tsx, package.json
Implemented a comprehensive "Report a Bug" page that matches the provided Figma design, featuring a fully functional bug reporting form with validation, file upload capabilities, and responsive design.
Closes #164 
- **Dark Theme Implementation**: Matched Figma design with custom CSS variables for consistent dark theme
- **Responsive Layout**: Mobile-first approach ensuring optimal experience across all devices
- **Component-Based Architecture**: Modular, reusable components following existing conventions
- **Form Fields**:
- Feedback Type selector (Bug Report/Feature Suggestion)
- Title field with validation
- Description textarea with validation
- Optional screenshot upload with drag & drop
- **Validation Rules**:
- Feedback type selection required
- Title: minimum 3 characters
- …
=> feat: implement report a bug page ui

components/explore/Navbar.tsx, components/explore/Sidebar.tsx, components/explore/home/LiveStreams.tsx, components/explore/home/TrendingStreams.tsx, components/settings/profile/avatar-modal.tsx, components/settings/profile/profile-header.tsx, components/settings/profile/profile-page.tsx, components/settings/profile/social-links-section.tsx, components/shared/profile/ProfileHeader.tsx, components/shared/profile/StreamCard.tsx, next.config.cjs
**Closes #184**
Fix the Settings Profile page to ensure all profile entities (Basic Info, Avatar, Social Links) can be properly updated and persisted. The form should allow users to update and fetch all profile data, with changes reflecting in the UI after submission. All updates should be fully integrated with the backend API.
---
- **Fixed Social Links Persistence:** Resolved case sensitivity mismatch between frontend (`socialLinks`) and backend (`sociallinks`) data structures
- **Enhanced Data Conversion:** Implemented robust `convertBackendSocialLinks` function to handle both array and object formats from backend
- **Improved State Management:** Added proper initialization and state handling for social links data
- **Theme Support:** Fixed social links section to properly support …
=> fix: settings profile entities update - resolve social links persistence and UI improvements

.gitignore, app/api/category/route.ts
Created Category Endpoints to create categories, to get all categories, to get a category by id and by search, to update a category, and to delete a category
_Closes #185 
Feature: Create Categories API Endpoints 
I created a route.ts file in the category folder in the API folder
=> Feat: 185-Category API Endpoints

app/[username]/layout.tsx, app/browse/layout.tsx, app/explore/layout.tsx, app/layout.tsx, app/settings/layout.tsx, components/SidebarWrapper.tsx, components/explore/Sidebar.tsx, components/ui/profileDropdown.tsx
=> update layout of all pages

app/explore/report-bug/page.tsx, components/SidebarWrapper.tsx, components/feedback/FeedbackHeader.tsx, components/feedback/FileUpload.tsx, components/feedback/ReportBugForm.tsx
- I fixed the report bug page making it light and dark mode compatible. 
_Closes #209_
- To make the report bug page responsive
- To make it light and dark mode compatible
- I made the report bug page light and dark mode compatible 
- I used the themes providing in the theme classes then used the tailwinds  `dark:` utility class for the specific colors not provided by the `theme-classes.ts`
- The page was already responsive so I focused more on the theming issues
Theme 
[Screencast from 2025-08-15 15-28-47.webm](https://github.com/user-attachments/assets/1792f1e0-a6f9-4700-b07c-eb6747cbc398)
Responsiveness
@Nwanne-san @davedumto 
Please review 🙏
=> fix: fixed the themeing issues for the report-bug page
